version = 3.11.3
runner.dialect = scala213

align.openParenCallSite = true
align.openParenDefnSite = true

maxColumn = 150
continuationIndent.defnSite = 2

assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true

rewrite.rules = [SortImports, RedundantParens, SortModifiers]

newlines.source = keep
newlines.afterCurlyLambda = preserve

spaces.inImportCurlyBraces = false

includeCurlyBraceInSelectChains = false
includeNoParensInSelectChains = false
optIn.breakChainOnFirstMethodDot = false

literals.long = Upper
literals.float = Upper
literals.double = Upper

docstrings = JavaDoc
docstrings.style = keep
docstrings.wrap = no
docstrings.oneline = keep
docstrings.blankFirstLine = keep
