addSbtPlugin("com.geirsson"   % "sbt-ci-release"     % "1.5.7")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"      % "1.8.2")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.13.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"           % "2.2.23")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin"    % "1.0.0")
