addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"       % "3.9.5")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"            % "2.1.1")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"      % "1.6.1")
addSbtPlugin("org.tpolecat"   % "tut-plugin"         % "0.6.13")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.10.1")