addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "1.1")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"       % "1.0.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "1.3.5")
addSbtPlugin("org.tpolecat"   % "tut-plugin"    % "0.4.2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
